baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vitality Fitness"
theme = "vitality-fitness"

[markup.goldmark.renderer]
unsafe= true

[menu]
  [[menu.main]]
    name = "Personal Training"
    url = "/personal-trainer-cardiff/"
    weight = 1

  [[menu.main]]
    name = "Sports Massage"
    url = "https://www.cardiffsportsmassage.co.uk/"
    weight = 2

  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3