baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vitality Fitness"
theme = "vitality-fitness"

[menu]
  [[menu.main]]
    name = "About Us"
    url = "/about/"

  [[menu.main]]
    name = "Vouchers"
    url = "/gift-vouchers/"

  [[menu.main]]
    name = "Prices"
    url = "/prices/"

  [[menu.main]]
    name = "Reviews"
    url = "/reviews/"

  [[menu.main]]
    name = "FAQ"
    url = "/faq/"

  [[menu.main]]
    name = "Contact"
    url = "/contact/"